name: iOS CI/CD

on:
  push:
    branches:
      - "master"
      - "developer"
  
  pull_request:
    branches:
      - "master"
      - "developer"
      
jobs:
 deploy_ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - name: Get run number
        run: |
          echo '${{ github.run_number }}'
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Install from Podfile
        run: |
          cd ios
          pod install
          cd .. 
      - name: FLutter build
        run: flutter build ios --release --no-codesign
      - name: FLutter build ipa
        run: flutter build ipa --obfuscate
      - name: Upload App File
        uses: actions/upload-artifact@v3
        with:
          name: app-release.app
          path: /Users/runner/work/fall2022/fall2022/build/ios/iphoneos/Runner.app
      - name: Upload Ipa File
        uses: actions/upload-artifact@v3
        with:
          name: app-release.ipa
          path: /build/ios/ipa
      - name: Run Unit Tests
        run: flutter test

